name: GitHub Actions Build and Deploy Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name:  Checkout 🛎️
      uses: actions/checkout@main

    - name: Install and Build 🔧 
      run: |
        npm install
        npm run build      

    - name: Deploy 🚀
      uses: June-tech/react-github-actions@main
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
    # - name: Build and Deploy
    #   uses: June-tech/react-github-actions@main
    #   env:
    #     # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: build
    #     BUILD_SCRIPT: npm install && npm run build
